default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres'%>
  password: <%= ENV['POSTGRES_PASSWD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: lead_score_development

test:
  <<: *default
  database: lead_score_test

production:
  <<: *default
  database: lead_score_production
